In [1]:
import cv2

In [10]:
image_path = r'Images/car.jpg'
image = cv2.imread(image_path)
cv2.imshow("Car", image)
gray_car = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("gray_car", gray_car)
cv2.imwrite("Graycar.jpg", gray_car)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
out2 = cv2.imread('Images/flower1.jpg')
cv2.imshow("PNG format", out2)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
import cv2 

# Display the rewritten image
out2 = cv2.imread(r'images\Tiger.png')
cv2.imshow('PNG Format', out2)

cv2.waitKey()
cv2.destroyAllWindows()

### Changing image color


In [15]:
image = cv2.imread("Images/Tiger.jpg")
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("ColourScale",image)
cv2.imshow('Grayscale', gray_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Another method to convert the image to grayscale and this is the faster method.
# 0 convert the inage to grayscale

In [18]:
image=cv2.imread("Images/Tiger.jpg", 0)
cv2.imshow('Grayscale', image)

cv2.waitKey()
cv2.destroyAllWindows()

### Individual Channels in RGB Images

In [3]:
image = cv2.imread('Images/large.jpg')
cv2.imshow("Image", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
B, G, R = cv2.split(image)
cv2.imshow("Red", R)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
cv2.imshow("Green", G)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
cv2.imshow("Blue", B)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Merge

In [7]:
import cv2
merged = cv2.merge([B,G, R ])
cv2.imshow("Merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Lets amplify the blue color

In [8]:
merged = cv2.merge([B+100, G, R+200])
cv2.imshow("Merged", merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Color Manipulation with numpy library

In [16]:
import numpy as np
b = np.zeros(2, dtype=int)
print ("Matrix b :\n", b)
a = np.zeros([2,2], dtype=int)
print("Matrix a : \n", a)
c = np.zeros([3, 3]) 
print("\nMatrix c : \n", c) 

Matrix b :
 [0 0]
Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
image.shape

(421, 748, 3)

In [25]:
image.shape[:1]

(421,)

In [26]:
image.shape[:2]

(421, 748)

In [29]:
image = cv2.imread('Images/Tiger.jpg')
B, G, R = cv2.split(image)
# Lets create a matrix of zeros with dimension of the image h* w
zeros = np.zeros(image.shape[:2], dtype = np.uint8)
print(zeros)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [36]:
path = 'images/large.jpg'

image = cv2.imread(path)

B, G, R = cv2.split(image)

zeros = np.zeros(image.shape[:2], dtype = "uint8")
cv2.imshow("red", cv2.merge([zeros, zeros, R]))
print(zeros)

cv2.waitKey()
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [37]:
cv2.imshow("Green", cv2.merge([zeros, G, zeros]))
cv2.waitKey()
cv2.destroyAllWindows()

In [38]:
cv2.imshow("Blue", cv2.merge([B, zeros, zeros]))
cv2.waitKey()
cv2.destroyAllWindows()

In [39]:
cv2.imshow("No color", cv2.merge([zeros, zeros, zeros]))
cv2.waitKey()
cv2.destroyAllWindows()

In [40]:
cv2.imshow("Re-Make", cv2.merge([B, G, R]))

cv2.waitKey()
cv2.destroyAllWindows()

### HSV (Hue, Saturation, and Value) Images
### H: 0 - 180, S: 0 - 255, V: 0 - 255



In [49]:
image = cv2.imread("Images/Tiger.jpg")
cv2.imshow("Tiger", image)

hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
cv2.imshow("HSv", hsv_image)

cv2.waitKey()
cv2.destroyAllWindows()

In [50]:
cv2.imshow("hue chanel", hsv_image[0:, 0 :, 0])
cv2.waitKey()
cv2.destroyAllWindows()

In [51]:
# Converting image into gray
# and resize in the image
cv2.imshow('Saturation channel', hsv_image[0:,0 :, 1])
cv2.waitKey()
cv2.destroyAllWindows()

In [52]:
# Converting image into black and white
# and resize in the image
cv2.imshow('Value channel', hsv_image[0:,0 :, 2])
cv2.waitKey()
cv2.destroyAllWindows()

### 2.7 Analysing Images using openCV Functions

In [54]:
# Let's look at the individual color levels for the first pixel (0,0)
import cv2
#import numpy as np

path = r'Images\clouds.jpg'
image = cv2.imread(path)

cv2.imshow('Clouds',image)

cv2.waitKey()
cv2.destroyAllWindows()

In [55]:
print(image.shape)

(1000, 1000, 3)


In [57]:
print("Height of the image", int(image.shape[0]), 'pixels')
print("Width of the image", int(image.shape[1]), 'pixels')

Height of the image 1000 pixels
Width of the image 1000 pixels


In [61]:
print(image.shape[:])
print(image.shape[:1])
print(image.shape[:2])
print(image.shape[1:])
print(image.shape[2:])

(1000, 1000, 3)
(1000,)
(1000, 1000)
(1000, 3)
(3,)


In [ ]:
B, G , R = image[0,0]
cv2.imshow("image", image[0,0])
cv2.waitKey()
cv2.destroyAllWindows()

In [65]:
# BGR Values for the first 0,0 pixel
B, G, R = image[0,0] 
print("Blue Value: ", B)
print("Green Value: ", G)
print("Red Value: ", R)

Blue Value:  203
Green Value:  137
Red Value:  58


In [66]:
# BGR Values for the last 829,1244 pixel
B, G, R = image[829,900] 
print("Blue Value: ", B)
print("Green Value: ", G)
print("Red Value: ", R)

Blue Value:  36
Green Value:  185
Red Value:  95


In [67]:
# Let's see what happens when we convert it to grayscale
gray_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print("Shape of the gray image: ", gray_img.shape)

Shape of the gray image:  (1000, 1000)


In [68]:
gray_img[0, 0] 

np.uint8(121)

In [70]:
gray_img[829, 900]

np.uint8(141)

In [71]:
gray_img[829,0]

np.uint8(147)

In [72]:
gray_img[0,999]

np.uint8(82)

In [75]:
input = cv2.imread('Images/affine.jpg')
cv2.imshow('Clouds',input)
print(input.shape)
cv2.waitKey()
cv2.destroyAllWindows()


(232, 194, 3)


In [76]:
# Let's see what happens when we convert it to hsv scale
hsv_image = cv2.cvtColor(input, cv2.COLOR_BGR2HSV)
print("Shape of the hsv image: ", hsv_image.shape)

Shape of the hsv image:  (232, 194, 3)


In [77]:
hsv_image[0,0]

array([140,   3, 242], dtype=uint8)