In [1]:
import cv2
import numpy as np

In [3]:
image =  np.zeros((200,200,3), np.uint8)
image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(200, 200, 3), dtype=uint8)

In [4]:
cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


### Black and white image

In [5]:
image_bw = np.zeros((512,512), np.uint8)
cv2.imshow("Black and white image", image_bw)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Extracting pixel information 

In [6]:
black = np.zeros([200,200,1], "uint8")
cv2.imshow("Black", black)
print(black)
print(black[0,0,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]]
[0]


Here I have used a list of [200,200,1]. The first part is the height in pixel, the second is the width of the image and the third is the channel. After that, you have to indicate the type of image. Like, in this case, I have used unsigned int of 8 bit. Therefore the values of the image type will from 0 to 255 (2 power of 8).

In [7]:
white = np.ones([200, 200, 3], "uint8")
white *= (2**8-1)
cv2.imshow("White",white)
print(white[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[255 255 255]


In [12]:
#rgb color
color = np.ones([200, 200, 3], "uint16")

#red color 
red = color.copy()
red[:,:]= (0, 0, 65535)
cv2.imshow("Red Color", red)
print(red[0, 0, :])

#blue color 
blue = color.copy()
blue[:,:]= (65535, 0 , 0)
cv2.imshow("Blue Color", blue)
print(blue[0, 0, :])

# green
green = color.copy()
green[:, :] = (0, 65535, 0)
cv2.imshow("Green Color", green)
print(green[0, 0, :])


cv2.waitKey(0)
cv2.destroyAllWindows()


[    0     0 65535]
[65535     0     0]
[    0 65535     0]


### Line and shapes

In [2]:
image = np.zeros((512, 512, 3), np.uint8)
cv2.line(image, (0,0), (511,511), (255, 255, 255), 3)
cv2.imshow("Image",image)

cv2.waitKey(0)
cv2.destroyAllWindows()

### rectangle

In [4]:
image = np.zeros((512, 512, 3), np.uint8)
cv2.rectangle(image, (100,100), (300, 250),(127,50,127),3)
cv2.imshow("Rectangle", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
cv2.rectangle(image, (100,100), (300,250), (127,50,127),5)

cv2.imshow("Rectangle", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

> -1 fill with the color

In [8]:
cv2.rectangle(image, (100,100), (300, 250), (127,50,127), -1)
cv2.imshow("rectangle", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

### circle

In [14]:
image = np.zeros((512, 512, 3), np.uint8)
cv2.circle(image, (100,150), 100,(255,255,255), 3)
cv2.imshow("circle", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
image = np.zeros((512, 512,3), np.uint8)
cv2.circle(image, (100,150), 100,(255,0,255), -1)
cv2.imshow("circle", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Polygons

In [26]:
image = np.zeros((512, 512, 3), np.uint8)
pts = np.array([[10,50],[400, 50], [90,200], [50,500]], np.int32)
# reshape pts required by polylines 
pts = pts.reshape((-1,1,2))
cv2.polylines(image, [pts], True, (0,0,255), 3)
cv2.imshow("Polygon", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
pts = np.array([[[10, 50], [400, 50], [90, 200], [50, 500]], 
                [[100, 100], [300, 100], [200, 300], [100, 400]]], np.int32)

# Reshape the points correctly for multiple polygons
pts = [p.reshape((-1, 1, 2)) for p in pts]

# Draw each polygon
for poly in pts:
    cv2.polylines(image, [poly], isClosed=True, color=(0, 0, 255), thickness=3)

# Show the image with the polygons
cv2.imshow("Polygons", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Ellipse

In [49]:
image = np.zeros((512, 512, 3), np.uint8)


color = (255,255,255)
thickness = 3
center_cordinates = (300,160)
axeslength = (200, 110)
angle = 90
startangle = 0
endangle = 360

cv2.ellipse(image, center_cordinates, axeslength, angle, startangle, endangle, color, thickness)

cv2.imshow("Elipse", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Text


In [54]:
image = np.zeros((512, 512, 3), np.uint8)
cv2.putText(image, "Hi, welcome", (40,60), cv2.FONT_HERSHEY_COMPLEX, 2, (100,150.200), 3)
cv2.imshow("Hello OpenCV World!", image)

cv2.waitKey(0)
cv2.destroyAllWindows()